from __future__ import annotations

from app.models.schemas import GeoPointFeature, GeoPointProperties, LayerDefinition


LAYER_CATALOG: list[LayerDefinition] = [
    LayerDefinition(
        id="pharmacies",
        label="Pharmacies",
        category="Sante",
        color="#1d4ed8",
        priority=1,
        visible_by_default=True,
        source_status="mock",
    ),
    LayerDefinition(
        id="health_professionals",
        label="Autres professionnels de sante",
        category="Sante",
        color="#0f766e",
        priority=2,
        visible_by_default=True,
        source_status="mock",
    ),
    LayerDefinition(
        id="public_transport",
        label="Transports publics",
        category="Mobilite",
        color="#7c3aed",
        priority=3,
        visible_by_default=True,
        source_status="mock",
    ),
    LayerDefinition(
        id="shops",
        label="Commerces utiles",
        category="Services",
        color="#c2410c",
        priority=4,
        visible_by_default=False,
        source_status="mock",
    ),
    LayerDefinition(
        id="points_of_interest",
        label="Points d'interet",
        category="Services",
        color="#be123c",
        priority=5,
        visible_by_default=False,
        source_status="mock",
    ),
]


MOCK_POINTS: list[GeoPointFeature] = [
    GeoPointFeature(
        geometry={"type": "Point", "coordinates": [2.3522, 48.8566]},
        properties=GeoPointProperties(
            id="pharm-1",
            layer="pharmacies",
            layer_label="Pharmacies",
            layer_color="#1d4ed8",
            name="Pharmacie Centrale",
            display_name="Pharmacie Centrale",
            city="Paris",
            address_line_1="10 rue de Rivoli",
            postal_code="75001",
            phone="01 42 00 00 01",
            source_name="mock_seed",
            geocode_status="resolved",
        ),
    ),
    GeoPointFeature(
        geometry={"type": "Point", "coordinates": [4.8357, 45.764]},
        properties=GeoPointProperties(
            id="pharm-2",
            layer="pharmacies",
            layer_label="Pharmacies",
            layer_color="#1d4ed8",
            name="Pharmacie des Terreaux",
            display_name="Pharmacie des Terreaux",
            city="Lyon",
            address_line_1="18 place des Terreaux",
            postal_code="69001",
            phone="04 72 00 00 02",
            source_name="mock_seed",
            geocode_status="resolved",
        ),
    ),
    GeoPointFeature(
        geometry={"type": "Point", "coordinates": [5.3698, 43.2965]},
        properties=GeoPointProperties(
            id="health-1",
            layer="health_professionals",
            layer_label="Autres professionnels de sante",
            layer_color="#0f766e",
            name="Cabinet Infirmier Vieux-Port",
            display_name="Cabinet Infirmier Vieux-Port",
            city="Marseille",
            address_line_1="5 quai du Port",
            postal_code="13002",
            source_name="mock_seed",
            geocode_status="resolved",
        ),
    ),
    GeoPointFeature(
        geometry={"type": "Point", "coordinates": [1.4442, 43.6047]},
        properties=GeoPointProperties(
            id="transport-1",
            layer="public_transport",
            layer_label="Transports publics",
            layer_color="#7c3aed",
            name="Station Jean Jaures",
            display_name="Station Jean Jaures",
            city="Toulouse",
            address_line_1="Place Jean Jaures",
            postal_code="31000",
            source_name="mock_seed",
            geocode_status="resolved",
        ),
    ),
    GeoPointFeature(
        geometry={"type": "Point", "coordinates": [-1.5536, 47.2184]},
        properties=GeoPointProperties(
            id="shop-1",
            layer="shops",
            layer_label="Commerces utiles",
            layer_color="#c2410c",
            name="Supermarche Centre",
            display_name="Supermarche Centre",
            city="Nantes",
            address_line_1="22 rue du Calvaire",
            postal_code="44000",
            source_name="mock_seed",
            geocode_status="resolved",
        ),
    ),
    GeoPointFeature(
        geometry={"type": "Point", "coordinates": [7.2619, 43.7102]},
        properties=GeoPointProperties(
            id="poi-1",
            layer="points_of_interest",
            layer_label="Points d'interet",
            layer_color="#be123c",
            name="Point d'accueil Riviera",
            display_name="Point d'accueil Riviera",
            city="Nice",
            address_line_1="12 promenade des Anglais",
            postal_code="06000",
            source_name="mock_seed",
            geocode_status="resolved",
        ),
    ),
]
